
export const name = 'hybrid-browser'
export const version = '3.0.3'
export const dependencies = {
  "@chainsafe/libp2p-gossipsub": "^13.2.0",
  "@derhuerst/gemini": "^2.0.0",
  "@helia/mfs": "^3.0.1",
  "@helia/unixfs": "^4.0.2",
  "@libp2p/identify": "^2.1.5",
  "@libp2p/kad-dht": "^12.1.5",
  "@roamhq/wrtc": "^0.8.0",
  "abort-controller": "^3.0.0",
  "blockstore-fs": "^1.1.10",
  "create-desktop-shortcuts": "^1.11.0",
  "data-uri-to-buffer": "^6.0.2",
  "datastore-fs": "^9.1.8",
  "decompress": "^4.2.1",
  "delay": "^6.0.0",
  "detect-port": "^1.5.1",
  "electron-extended-webextensions": "github:HybridWare/electron-extended-WebExtensions",
  "event-iterator": "^2.0.0",
  "fs-extra": "^11.2.0",
  "gemini-to-html": "^2.1.0",
  "gopher-lib": "^0.2.0",
  "helia": "^5.2.0",
  "http-proxy-agent": "^7.0.2",
  "hyper-sdk": "^4.5.0",
  "mime": "^4.0.1",
  "multiformats": "^9.9.0",
  "node-fetch": "^3.3.2",
  "p-queue": "^8.0.1",
  "range-parser": "^1.2.1",
  "rc": "^1.2.8",
  "sanitize-filename": "^1.6.3",
  "scoped-fs": "^1.4.1",
  "semver": "^7.6.3",
  "socks-proxy-agent": "^8.0.2",
  "streamx": "^2.16.1",
  "torrentz": "^18.0.3",
  "whatwg-mimetype": "github:jsdom/whatwg-mimetype",
  "wrtc": "^0.4.7",
  "ws": "^8.18.0"
}
