
export const name = 'hybrid-browser'
export const version = '3.0.0'
export const dependencies = {
  "@derhuerst/gemini": "^2.0.0",
  "@helia/mfs": "^3.0.1",
  "@helia/unixfs": "^3.0.1",
  "abort-controller": "^3.0.0",
  "blockstore-fs": "^1.1.10",
  "create-desktop-shortcuts": "^1.11.0",
  "data-uri-to-buffer": "^6.0.2",
  "datastore-fs": "^9.1.8",
  "decompress": "^4.2.1",
  "delay": "^6.0.0",
  "detect-port": "^1.5.1",
  "electron-extended-webextensions": "github:ducksandgoats/electron-extended-WebExtensions",
  "fs-extra": "^11.2.0",
  "gemini-to-html": "^2.1.0",
  "get-urls": "^12.1.0",
  "gopher-lib": "^0.2.0",
  "helia": "^4.0.2",
  "http-proxy-agent": "^7.0.2",
  "hyper-sdk": "^4.5.0",
  "mime": "^4.0.1",
  "multiformats": "^13.1.0",
  "node-fetch": "^3.3.2",
  "range-parser": "^1.2.1",
  "rc": "^1.2.8",
  "sanitize-filename": "^1.6.3",
  "scoped-fs": "^1.4.1",
  "socks-proxy-agent": "^8.0.2",
  "streamx": "^2.16.1",
  "torrentz": "^14.0.8",
  "whatwg-mimetype": "github:jsdom/whatwg-mimetype",
  "wrtc": "^0.4.7"
}
