
export const name = 'hybrid-browser'
export const version = '3.0.5'
export const dependencies = {
  "@chainsafe/libp2p-gossipsub": "^14.1.0",
  "@derhuerst/gemini": "^2.0.0",
  "@helia/unixfs": "^4.0.2",
  "@libp2p/identify": "^3.0.15",
  "@libp2p/kad-dht": "^14.2.0",
  "abort-controller": "^3.0.0",
  "blockstore-fs": "^2.0.2",
  "create-desktop-shortcuts": "^1.11.0",
  "data-uri-to-buffer": "^6.0.2",
  "datastore-fs": "^10.0.2",
  "decompress": "^4.2.1",
  "delay": "^6.0.0",
  "detect-port": "^2.1.0",
  "electron-extended-webextensions": "github:HybridWare/electron-extended-WebExtensions",
  "event-iterator": "^2.0.0",
  "fs-extra": "^11.3.0",
  "gopher-lib": "^0.2.0",
  "helia": "^5.2.0",
  "http-proxy-agent": "^7.0.2",
  "hyper-sdk": "^5.1.0",
  "ipfs-pubsub-room": "github:ducksandgoats/ipfs-pubsub-room",
  "mime": "^4.0.6",
  "multiformats": "^9.9.0",
  "node-fetch": "^3.3.2",
  "p-queue": "^8.1.0",
  "range-parser": "^1.2.1",
  "rc": "^1.2.8",
  "sanitize-filename": "^1.6.3",
  "scoped-fs": "^1.4.1",
  "semver": "^7.7.0",
  "socks-proxy-agent": "^8.0.5",
  "streamx": "^2.22.0",
  "torrentz": "^19.0.7",
  "uint8-util": "^2.2.5",
  "whatwg-mimetype": "github:jsdom/whatwg-mimetype"
}
